services:
  - type: web
    name: color-clash
    runtime: node
    buildCommand: npm install && npm run build -w client
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
